# For environment variables see the README.md

networks:
  wordsmith:
    driver: bridge

volumes:
  wwwroot:
  book-storage:
  mysql-data:
  rabbitmq-data:
  rabbitmq-logs:


services:
  wordsmith-api:
    container_name: wordsmith-api
    hostname: wordsmith-api
    image: wordsmith/wordsmith-api:latest
    build:
      context: .
      dockerfile: Wordsmith.API/Dockerfile
    restart: unless-stopped
    depends_on:
      - wordsmith-identityserver
      - wordsmith-db
      - wordsmith-rabbitmq
    ports:
      - 6443:443 # HTTPS
    environment:
      - WORDSMITH_Connection__IdentityServer__Host=wordsmith-identityserver
      - WORDSMITH_Connection__MySQL__Host=wordsmith-db
      - WORDSMITH_Connection__MySQL__Port=3306
      - WORDSMITH_Connection__MySQL__User=wordsmith_user
      - WORDSMITH_Connection__MySQL__Password=wordsmith_user
      - WORDSMITH_Connection__MySQL__Database=wordsmith
      - WORDSMITH_Connection__RabbitMQ__Host=wordsmith-rabbitmq
      - WORDSMITH_Connection__RabbitMQ__User=wordsmith_user
      - WORDSMITH_Connection__RabbitMQ__Password=wordsmith_user
      - WORDSMITH_PayPalClientId=<SET HERE>
      - WORDSMITH_PayPalClientSecret=<SET HERE>
    networks:
      - wordsmith
    volumes:
      - wwwroot:/wwwroot
      - book-storage:/app/books

  wordsmith-identityserver:
    container_name: wordsmith-identityserver
    hostname: wordsmith-identityserver
    image: wordsmith/wordsmith-identityserver:latest
    build:
      context: .
      dockerfile: Wordsmith.IdentityServer/Dockerfile
    restart: unless-stopped
    depends_on:
      - wordsmith-db
      - wordsmith-rabbitmq
    ports:
      - 7443:443 # HTTPS
    environment:
      - WORDSMITH_Connection__IdentityServer__Host=wordsmith-identityserver
      - WORDSMITH_Connection__MySQL__Host=wordsmith-db
      - WORDSMITH_Connection__MySQL__Port=3306
      - WORDSMITH_Connection__MySQL__User=wordsmith_user
      - WORDSMITH_Connection__MySQL__Password=wordsmith_user
      - WORDSMITH_Connection__MySQL__Database=wordsmith
      - WORDSMITH_Connection__RabbitMQ__Host=wordsmith-rabbitmq
      - WORDSMITH_Connection__RabbitMQ__User=wordsmith_user
      - WORDSMITH_Connection__RabbitMQ__Password=wordsmith_user
    networks:
      - wordsmith

  wordsmith-db:
    container_name: wordsmith-db
    hostname: wordsmith-db
    image: mysql:latest
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=wordsmith_root_password
      - MYSQL_USER=wordsmith_user
      - MYSQL_PASSWORD=wordsmith_user
      - MYSQL_DATABASE=wordsmith
    networks:
      - wordsmith
    volumes:
      - mysql-data:/var/lib/mysql

  wordsmith-rabbitmq:
    container_name: wordsmith-rabbitmq
    hostname: wordsmith-rabbitmq
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=wordsmith_user
      - RABBITMQ_DEFAULT_PASS=wordsmith_user
    networks:
      - wordsmith
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - rabbitmq-logs:/var/log/rabbitmq
