name: Build and analize with Qodana

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies (API)
      run: dotnet restore Wordsmith.API/Wordsmith.API.csproj

    - name: Restore dependencies (IdentityServer)
      run: dotnet restore Wordsmith.IdentityServer/Wordsmith.IdentityServer.csproj

    - name: Restore dependencies (CommunicationsRelay)
      run: dotnet restore Wordsmith.CommunicationsRelay/Wordsmith.CommunicationsRelay.csproj
      
    - name: Build (API)
      run: dotnet build --no-restore Wordsmith.API/Wordsmith.API.csproj

    - name: Build (IdentityServer)
      run: dotnet build --no-restore Wordsmith.IdentityServer/Wordsmith.IdentityServer.csproj
      
    - name: Build (CommunicationsRelay)
      run: dotnet build --no-restore Wordsmith.CommunicationsRelay/Wordsmith.CommunicationsRelay.csproj

  # qodana:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: write
  #     pull-requests: write
  #     checks: write
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
  #         fetch-depth: 0  # a full history is required for pull request analysis
          
  #     - name: 'Qodana Scan'
  #       uses: JetBrains/qodana-action@v2023.3
  #       env:
  #         QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
